In [ ]:
x <- TRUE   # alt-
y <- FALSE
class(x);class(y)

[1] "logical"

[1] "logical"

In [4]:
x <- matrix(1:20, 5, 4)
x
class(x)

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   18  
[4,] 4     9   14   19  
[5,] 5    10   15   20

[1] "matrix"

In [5]:
x[1, 2]   # 행, 열 순으로 지정해서 한 값만 뽑아내기 가능

[1] 6

In [6]:
matrix(1:20, 5, 4, byrow = TRUE)   # 행 먼저 채우고 열 채우는 방법

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16  
[5,] 17   18   19   20

In [9]:
x <- array(1:2, c(5, 4, 2))
x
class(x)

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    2    1    2
[2,]    2    1    2    1
[3,]    1    2    1    2
[4,]    2    1    2    1
[5,]    1    2    1    2

, , 2

     [,1] [,2] [,3] [,4]
[1,]    1    2    1    2
[2,]    2    1    2    1
[3,]    1    2    1    2
[4,]    2    1    2    1
[5,]    1    2    1    2

[1] "array"

In [10]:
x <- list(c(1:5), c(1:50))
x

[[1]]
[1] 1 2 3 4 5

[[2]]
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50

In [13]:
x <- list(flower = "rose", color = c("red", "white"))
x
x[1]

$flower
[1] "rose"

$color
[1] "red"   "white"

$flower
[1] "rose"

In [17]:
df <- data.frame(name = c("kim", "ahn", "lee", "park"), age = c(32, 25, 18, 39), height = c(170, 175, 168, 180), weight = c(63, 66, 59, 70))
df
class(df)

name age height weight
1 kim  32  170    63    
2 ahn  25  175    66    
3 lee  18  168    59    
4 park 39  180    70

[1] "data.frame"

In [35]:
name <- c("kim", "ahn", "lee", "park")
age <- c(32, 25, 18, 39)
weight <- c(63, 66, 59, 70)
height <- c(170, 175, 168, 180)
df <- data.frame(name, age, height, weight)
df

name age height weight
1 kim  32  170    63    
2 ahn  25  175    66    
3 lee  18  168    59    
4 park 39  180    70

In [25]:
df[1, ]
df[3, ]
df[c(1, 3), ]

name age height weight
1 kim  32  170    63

name age height weight
3 lee  18  168    59

name age height weight
1 kim  32  170    63    
3 lee  18  168    59

In [28]:
df[ , 2]
df[ , 2, drop = FALSE]   # 원래 형태대로 하고싶으면 저거 써라

[1] 32 25 18 39

age
1 32 
2 25 
3 18 
4 39

In [30]:
rownames(df) <- c("one", "two", "three", "four")   # rownames: 행 이름을 붙이는 함수
df

name age height weight
one   kim  32  170    63    
two   ahn  25  175    66    
three lee  18  168    59    
four  park 39  180    70

In [33]:
df[c("one", "three"),]
df[ , "age", drop = FALSE]

name age height weight
one   kim  32  170    63    
three lee  18  168    59

age
one   32 
two   25 
three 18 
four  39

In [34]:
df$height

[1] 170 175 168 180

In [67]:
이름 <- c("민준", "유리", "재희")
나이 <- c(22, 20, 21)
성별 <- c("남", "여", "남")
전공 <- c("수학", "영문", "경영")
df <- data.frame(이름, 나이, 성별, 전공)
rownames(df) <- c('0', '1', '2')
##########################################
# 1. 데이터 프레임
df
##########################################
# 2. 열별로 전부 각각 데이터 추출하기
df$이름
df$나이
df$성별
df$전공
##########################################
# 3. 행별로 전부 각각 데이터 추출하기
df[1, ]
df[2, ]
df[3, ]
##########################################
# 4. 유리와 재희의 정보만 추출하기
df[2:3, ]
##########################################
# 5. 나이와 성별의 정보만 추출하기
df$나이
df$성별
##########################################
# 6. 나이의 평균
(df[1, 2] + df[2, 2] + df[3, 2])/3
##########################################
# 7. 성별 인원수


이름 나이 성별 전공
0 민준 22   남   수학
1 유리 20   여   영문
2 재희 21   남   경영

[1] 민준 유리 재희
Levels: 민준 유리 재희

[1] 22 20 21

[1] 남 여 남
Levels: 남 여

[1] 수학 영문 경영
Levels: 경영 수학 영문

이름 나이 성별 전공
0 민준 22   남   수학

이름 나이 성별 전공
1 유리 20   여   영문

이름 나이 성별 전공
2 재희 21   남   경영

이름 나이 성별 전공
1 유리 20   여   영문
2 재희 21   남   경영

[1] 22 20 21

[1] 남 여 남
Levels: 남 여

[1] 21